### ISSUE TITLE
ProbCover

### ISSUE THREAD

**Issue by cliangyu** [avihu111/TypiClust#1]
Hi! Can I expect ProbCover implementation in this repo? 👀

**Comment by avihu111** [comment]
Hi Liangyu, 

Thanks for your interest in our work! 
I'll try push an implementation for ProbCover in the next week.
I'll update when it's ready.

**Comment by avihu111** [comment]
Hi Liangyu,

I uploaded a ProbCover implementation. 
[Check out the changes here.](https://github.com/avihu111/TypiClust/pull/2/files)

Usage example:
```
python train_al.py --cfg ../configs/cifar100/al/RESNET18.yaml --al probcover --exp-name auto --initial_size 0 --budget 100 --delta 0.6
```

I'm closing this issue for now, feel free to reopen it.
