### ISSUE TITLE
test_features_seed1.npy 

### ISSUE THREAD

**Issue by bardisafa** [avihu111/TypiClust#4]
Hello, 

I have downloaded "features_seed1.npy" from the provided link, however, the code also needs "test_features_seed1.npy" to run. Could you let me know where can I download it?

Thanks

**Comment by avihu111** [comment]
Hi,

We just added the test features and you can now find them in here:
https://github.com/avihu111/TypiClust/blob/main/USAGE.md

Alternatively, you can train SimCLR (see representation learning section in USAGE) and extract the features.
Feel free to re-open this issue if you need something else.
Thanks!

**Comment by lu-zhang1** [comment]
Hi avihu111,

There are no test features in the link you provided. Are they removed? 

Thanks,
